import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FeedPost } from '@interfaces/feed-post.interface';
import { LucideAngularModule, Users, UserPlus, EllipsisVertical, X, Eye, MessageCircle, User } from 'lucide-angular';

@Component({
  selector: 'component-student-portfolio-personal',
  imports: [
    LucideAngularModule,
    CommonModule
  ],
  templateUrl: './personal.component.html',
})
export class ComponentStudentPortfolioPersonal {

  readonly User = User;
  readonly Users = Users;
  readonly UserPlus = UserPlus;
  readonly EllipsisVertical = EllipsisVertical;
  readonly X = X;
  readonly Eye = Eye;
  readonly MessageCircle = MessageCircle;

  posts: FeedPost[] = [
    {
      id: '21',
      user: { id: 'u21', name: 'Eduardo', lastName: 'De La Torre', profilePicture: null, role: 'Estudiante' },
      title: 'Aplicación móvil para control de gastos personales',
      content: 'Desarrollo de una app que permite registrar ingresos y egresos, generar reportes y recomendaciones de ahorro.',
      hashtags: ['Finanzas', 'Flutter', 'Mobile'],
      createdAt: '2025-10-05T09:00:00',
      type: 'proyecto',
      isCollaborative: false,
      team: { members: [], count: 0, names: '' },
      document: { name: 'Repositorio GitHub', url: 'https://github.com/sofia/app-gastos' },
      likes: 120,
      likedByCurrentUser: false,
      comments: 10
    },
    {
      id: '22',
      user: { id: 'u21', name: 'Eduardo', lastName: 'De La Torre', profilePicture: null, role: 'Estudiante' },
      title: 'Investigación sobre la influencia de la música clásica en la concentración',
      content: 'Idea de estudio experimental con estudiantes de distintas carreras midiendo niveles de concentración.',
      hashtags: ['Psicología', 'Música', 'Investigación'],
      createdAt: '2025-10-05T10:15:00',
      type: 'idea',
      isCollaborative: false,
      team: { members: [], count: 0, names: '' },
      document: { name: 'Propuesta.pdf', url: 'https://drive.google.com/ejemplo/musica-concentracion' },
      likes: 80,
      likedByCurrentUser: true,
      comments: 6
    },
    {
      id: '23',
      user: { id: 'u21', name: 'Eduardo', lastName: 'De La Torre', profilePicture: null, role: 'Estudiante' },
      title: 'Prototipo de brazo robótico con Arduino',
      content: 'Creación de un brazo robótico básico controlado por servomotores y Arduino.',
      hashtags: ['Arduino', 'Robótica', 'Ingeniería'],
      createdAt: '2025-10-05T11:30:00',
      type: 'proyecto',
      isCollaborative: false,
      team: { members: [], count: 0, names: '' },
      document: { name: 'Código.zip', url: 'https://drive.google.com/ejemplo/robot' },
      likes: 145,
      likedByCurrentUser: false,
      comments: 12
    },
    {
      id: '24',
      user: { id: 'u21', name: 'Eduardo', lastName: 'De La Torre', profilePicture: null, role: 'Estudiante' },
      title: 'Estudio sobre el impacto del café en los patrones de sueño universitarios',
      content: 'Idea de investigación para analizar cómo afecta la cafeína al descanso de estudiantes.',
      hashtags: ['Salud', 'Sueño', 'Café'],
      createdAt: '2025-10-05T12:00:00',
      type: 'idea',
      isCollaborative: false,
      team: { members: [], count: 0, names: '' },
      document: { name: 'Resumen.docx', url: 'https://drive.google.com/ejemplo/cafe-sueno' },
      likes: 95,
      likedByCurrentUser: false,
      comments: 8
    },
    {
      id: '25',
      user: { id: 'u21', name: 'Eduardo', lastName: 'De La Torre', profilePicture: null, role: 'Estudiante' },
      title: 'Página web de recetas saludables',
      content: 'Proyecto personal de un sitio web con recetas nutritivas y fáciles de preparar.',
      hashtags: ['HTML', 'CSS', 'Nutrición'],
      createdAt: '2025-10-05T12:40:00',
      type: 'proyecto',
      isCollaborative: false,
      team: { members: [], count: 0, names: '' },
      document: { name: 'Sitio Web', url: 'https://ejemplo.com/recetas' },
      likes: 130,
      likedByCurrentUser: true,
      comments: 14
    },
    {
      id: '26',
      user: { id: 'u21', name: 'Eduardo', lastName: 'De La Torre', profilePicture: null, role: 'Estudiante' },
      title: 'App para aprender vocabulario en inglés',
      content: 'Diseño de aplicación móvil con juegos interactivos para memorizar palabras en inglés.',
      hashtags: ['Educación', 'Idiomas', 'Mobile'],
      createdAt: '2025-10-05T13:15:00',
      type: 'idea',
      isCollaborative: false,
      team: { members: [], count: 0, names: '' },
      document: { name: 'Wireframes.png', url: 'https://drive.google.com/ejemplo/vocabulario' },
      likes: 110,
      likedByCurrentUser: false,
      comments: 9
    },
    {
      id: '27',
      user: { id: 'u21', name: 'Eduardo', lastName: 'De La Torre', profilePicture: null, role: 'Estudiante' },
      title: 'Modelo de predicción de rendimiento académico con machine learning',
      content: 'Proyecto en Python que analiza notas previas para predecir el desempeño futuro de los alumnos.',
      hashtags: ['Python', 'Machine Learning', 'Educación'],
      createdAt: '2025-10-05T14:00:00',
      type: 'proyecto',
      isCollaborative: false,
      team: { members: [], count: 0, names: '' },
      document: { name: 'Repositorio GitHub', url: 'https://github.com/sofia/prediccion' },
      likes: 160,
      likedByCurrentUser: true,
      comments: 18
    },
    {
      id: '28',
      user: { id: 'u21', name: 'Eduardo', lastName: 'De La Torre', profilePicture: null, role: 'Estudiante' },
      title: 'Investigación sobre hábitos de lectura en adolescentes',
      content: 'Propuesta de estudio para identificar patrones de lectura digital y física en jóvenes.',
      hashtags: ['Lectura', 'Educación', 'Psicología'],
      createdAt: '2025-10-05T14:30:00',
      type: 'idea',
      isCollaborative: false,
      team: { members: [], count: 0, names: '' },
      document: { name: 'Encuesta.xlsx', url: 'https://drive.google.com/ejemplo/lectura' },
      likes: 70,
      likedByCurrentUser: false,
      comments: 5
    },
    {
      id: '29',
      user: { id: 'u21', name: 'Eduardo', lastName: 'De La Torre', profilePicture: null, role: 'Estudiante' },
      title: 'Sistema de inventario para pequeñas tiendas',
      content: 'Desarrollo de software en Java para controlar stock, ventas y reportes en negocios pequeños.',
      hashtags: ['Java', 'Inventario', 'Negocios'],
      createdAt: '2025-10-05T15:00:00',
      type: 'proyecto',
      isCollaborative: false,
      team: { members: [], count: 0, names: '' },
      document: { name: 'Manual.docx', url: 'https://drive.google.com/ejemplo/inventario' },
      likes: 175,
      likedByCurrentUser: true,
      comments: 22
    },
    {
      id: '30',
      user: { id: 'u21', name: 'Eduardo', lastName: 'De La Torre', profilePicture: null, role: 'Estudiante' },
      title: 'Plataforma de cursos en línea para artes plásticas',
      content: 'Idea de portal web para conectar artistas con estudiantes interesados en pintura y escultura.',
      hashtags: ['Arte', 'Educación', 'Web'],
      createdAt: '2025-10-05T15:40:00',
      type: 'idea',
      isCollaborative: false,
      team: { members: [], count: 0, names: '' },
      document: { name: 'Presentación.pptx', url: 'https://drive.google.com/ejemplo/cursos-artes' },
      likes: 85,
      likedByCurrentUser: false,
      comments: 7
    },
    {
      id: '31',
      user: { id: 'u21', name: 'Eduardo', lastName: 'De La Torre', profilePicture: null, role: 'Estudiante' },
      title: 'App de recordatorios médicos para adultos mayores',
      content: 'Aplicación móvil que envía alertas sobre medicación y citas médicas.',
      hashtags: ['Salud', 'Mobile', 'Usabilidad'],
      createdAt: '2025-10-05T16:15:00',
      type: 'proyecto',
      isCollaborative: false,
      team: { members: [], count: 0, names: '' },
      document: { name: 'APK Beta', url: 'https://drive.google.com/ejemplo/medicina' },
      likes: 200,
      likedByCurrentUser: true,
      comments: 25
    },
    {
      id: '32',
      user: { id: 'u21', name: 'Eduardo', lastName: 'De La Torre', profilePicture: null, role: 'Estudiante' },
      title: 'Estudio de impacto ambiental en campus universitarios',
      content: 'Investigación para medir el consumo energético y la huella de carbono en instalaciones educativas.',
      hashtags: ['MedioAmbiente', 'Sostenibilidad', 'Educación'],
      createdAt: '2025-10-05T17:00:00',
      type: 'idea',
      isCollaborative: false,
      team: { members: [], count: 0, names: '' },
      document: { name: 'Informe preliminar.pdf', url: 'https://drive.google.com/ejemplo/ambiental' },
      likes: 100,
      likedByCurrentUser: false,
      comments: 11
    },
    {
      id: '33',
      user: { id: 'u21', name: 'Eduardo', lastName: 'De La Torre', profilePicture: null, role: 'Estudiante' },
      title: 'Sistema de reservas para consultorios odontológicos',
      content: 'Software web que permite a pacientes agendar citas y a doctores gestionar horarios.',
      hashtags: ['Web', 'Salud', 'Reservas'],
      createdAt: '2025-10-05T17:45:00',
      type: 'proyecto',
      isCollaborative: false,
      team: { members: [], count: 0, names: '' },
      document: { name: 'Demo Web', url: 'https://ejemplo.com/odontologia' },
      likes: 155,
      likedByCurrentUser: true,
      comments: 14
    },
    {
      id: '34',
      user: { id: 'u21', name: 'Eduardo', lastName: 'De La Torre', profilePicture: null, role: 'Estudiante' },
      title: 'Investigación sobre el impacto de redes sociales en autoestima adolescente',
      content: 'Idea de estudio con encuestas y entrevistas para analizar la influencia de redes sociales.',
      hashtags: ['Psicología', 'RedesSociales', 'Juventud'],
      createdAt: '2025-10-05T18:20:00',
      type: 'idea',
      isCollaborative: false,
      team: { members: [], count: 0, names: '' },
      document: { name: 'Encuesta.xlsx', url: 'https://drive.google.com/ejemplo/redes' },
      likes: 90,
      likedByCurrentUser: false,
      comments: 8
    },
    {
      id: '35',
      user: { id: 'u21', name: 'Eduardo', lastName: 'De La Torre', profilePicture: null, role: 'Estudiante' },
      title: 'Plataforma de trueque de libros universitarios',
      content: 'Web que conecta estudiantes para intercambiar o vender libros usados.',
      hashtags: ['Web', 'Educación', 'Emprendimiento'],
      createdAt: '2025-10-05T19:00:00',
      type: 'proyecto',
      isCollaborative: false,
      team: { members: [], count: 0, names: '' },
      document: { name: 'Repositorio GitHub', url: 'https://github.com/sofia/libros' },
      likes: 175,
      likedByCurrentUser: true,
      comments: 20
    },
    {
      id: '36',
      user: { id: 'u21', name: 'Eduardo', lastName: 'De La Torre', profilePicture: null, role: 'Estudiante' },
      title: 'App para planificar entrenamientos en casa',
      content: 'Aplicación móvil que genera rutinas de ejercicio personalizadas sin necesidad de gimnasio.',
      hashtags: ['Deporte', 'Salud', 'Mobile'],
      createdAt: '2025-10-05T19:40:00',
      type: 'idea',
      isCollaborative: false,
      team: { members: [], count: 0, names: '' },
      document: { name: 'Prototipo.fig', url: 'https://drive.google.com/ejemplo/fitness' },
      likes: 140,
      likedByCurrentUser: false,
      comments: 13
    },
    {
      id: '37',
      user: { id: 'u21', name: 'Eduardo', lastName: 'De La Torre', profilePicture: null, role: 'Estudiante' },
      title: 'Sistema para gestión de talleres de arte en colegios',
      content: 'Plataforma que organiza horarios, inscripciones y materiales para cursos de pintura y música.',
      hashtags: ['Arte', 'Educación', 'Gestión'],
      createdAt: '2025-10-05T20:20:00',
      type: 'proyecto',
      isCollaborative: false,
      team: { members: [], count: 0, names: '' },
      document: { name: 'Plan.docx', url: 'https://drive.google.com/ejemplo/talleres' },
      likes: 115,
      likedByCurrentUser: true,
      comments: 9
    },
    {
      id: '38',
      user: { id: 'u21', name: 'Eduardo', lastName: 'De La Torre', profilePicture: null, role: 'Estudiante' },
      title: 'Investigación sobre el uso de IA en diagnósticos médicos',
      content: 'Análisis de herramientas de machine learning aplicadas a imágenes radiológicas.',
      hashtags: ['IA', 'Medicina', 'MachineLearning'],
      createdAt: '2025-10-05T21:00:00',
      type: 'idea',
      isCollaborative: false,
      team: { members: [], count: 0, names: '' },
      document: { name: 'Paper.pdf', url: 'https://drive.google.com/ejemplo/ia-medica' },
      likes: 210,
      likedByCurrentUser: false,
      comments: 30
    },
    {
      id: '39',
      user: { id: 'u21', name: 'Eduardo', lastName: 'De La Torre', profilePicture: null, role: 'Estudiante' },
      title: 'Chatbot para orientación vocacional',
      content: 'Proyecto en Python que recomienda carreras a jóvenes según sus intereses y aptitudes.',
      hashtags: ['Python', 'Chatbot', 'Educación'],
      createdAt: '2025-10-05T21:30:00',
      type: 'proyecto',
      isCollaborative: false,
      team: { members: [], count: 0, names: '' },
      document: { name: 'Código GitHub', url: 'https://github.com/sofia/chatbot-vocacional' },
      likes: 165,
      likedByCurrentUser: true,
      comments: 17
    },
    {
      id: '40',
      user: { id: 'u21', name: 'Eduardo', lastName: 'De La Torre', profilePicture: null, role: 'Estudiante' },
      title: 'Aplicación de meditación guiada',
      content: 'App con sesiones de audio y respiración para reducir estrés en estudiantes.',
      hashtags: ['Salud', 'Bienestar', 'Mobile'],
      createdAt: '2025-10-05T22:00:00',
      type: 'idea',
      isCollaborative: false,
      team: { members: [], count: 0, names: '' },
      document: { name: 'Mockup.png', url: 'https://drive.google.com/ejemplo/meditacion' },
      likes: 185,
      likedByCurrentUser: true,
      comments: 19
    }
  ];

}
